version: '3.8'

services:
  pr-documentator:
    build: .
    ports:
      - "8443:8443"
    environment:
      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8443
      - SERVER_READ_TIMEOUT=15s
      - SERVER_WRITE_TIMEOUT=15s
      
      # TLS Configuration
      - TLS_CERT_FILE=./certs/server.crt
      - TLS_KEY_FILE=./certs/server.key
      
      # Claude API Configuration
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-sonnet-20240229}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS:-4096}
      - CLAUDE_BASE_URL=${CLAUDE_BASE_URL:-https://api.anthropic.com}
      - CLAUDE_TIMEOUT=${CLAUDE_TIMEOUT:-30s}
      
      # Postman API Configuration
      - POSTMAN_API_KEY=${POSTMAN_API_KEY}
      - POSTMAN_WORKSPACE_ID=${POSTMAN_WORKSPACE_ID}
      - POSTMAN_COLLECTION_ID=${POSTMAN_COLLECTION_ID}
      - POSTMAN_BASE_URL=${POSTMAN_BASE_URL:-https://api.postman.com}
      - POSTMAN_TIMEOUT=${POSTMAN_TIMEOUT:-30s}
      
      # GitHub Configuration
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "-q", "--spider", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s